import '../../features/auth/data/models/user_model.dart';
import '../../features/grades/data/models/grade_model.dart';

/// Identifiants de démonstration pour le Play Store
class DemoCredentials {
  static const String username = 'demo@bahut.app';
  static const String password = 'demo2024';

  static bool isDemo(String username, String password) {
    return username.toLowerCase() == DemoCredentials.username &&
        password == DemoCredentials.password;
  }
}

/// Données de démonstration
class DemoData {
  /// Utilisateur démo
  static UserModel get demoUser => const UserModel(
        id: 99999,
        nom: 'DUPONT',
        prenom: 'Parent',
        typeCompte: 'P',
        email: 'demo@bahut.app',
      );

  /// Enfant démo
  static ChildModel get demoChild => const ChildModel(
        id: 99998,
        nom: 'DUPONT',
        prenom: 'Marie',
        classe: '3ème A',
        classeId: 1234,
        sexe: 'F',
      );

  /// Périodes scolaires démo
  static List<PeriodModel> get demoPeriods => [
        PeriodModel(
          codePeriode: 'A001',
          periode: 'Trimestre 1',
          dateDebut: '2025-09-01',
          dateFin: '2025-12-15',
          cloture: true,
        ),
        PeriodModel(
          codePeriode: 'A002',
          periode: 'Trimestre 2',
          dateDebut: '2026-01-06',
          dateFin: '2026-03-20',
          cloture: false,
        ),
        PeriodModel(
          codePeriode: 'A003',
          periode: 'Trimestre 3',
          dateDebut: '2026-04-06',
          dateFin: '2026-06-30',
          cloture: false,
        ),
      ];

  /// Notes de démonstration
  static List<GradeModel> get demoGrades => [
        // ===== MATHÉMATIQUES =====
        const GradeModel(
          id: 1001,
          devoir: 'Contrôle - Théorème de Pythagore',
          codePeriode: 'A001',
          codeMatiere: 'MATHS',
          libelleMatiere: 'Mathématiques',
          coef: '2',
          noteSur: '20',
          valeur: '16',
          date: '2025-09-20',
          moyenneClasse: '12,5',
          minClasse: '4',
          maxClasse: '18',
        ),
        const GradeModel(
          id: 1002,
          devoir: 'DM - Fonctions linéaires',
          codePeriode: 'A001',
          codeMatiere: 'MATHS',
          libelleMatiere: 'Mathématiques',
          coef: '1',
          noteSur: '20',
          valeur: '14',
          date: '2025-10-05',
          moyenneClasse: '11,8',
        ),
        const GradeModel(
          id: 1003,
          devoir: 'Interrogation - Calcul littéral',
          codePeriode: 'A001',
          codeMatiere: 'MATHS',
          libelleMatiere: 'Mathématiques',
          coef: '1',
          noteSur: '10',
          valeur: '8',
          date: '2025-11-12',
          moyenneClasse: '6,2',
        ),
        const GradeModel(
          id: 1004,
          devoir: 'Contrôle - Équations',
          codePeriode: 'A002',
          codeMatiere: 'MATHS',
          libelleMatiere: 'Mathématiques',
          coef: '2',
          noteSur: '20',
          valeur: '15',
          date: '2026-01-15',
          moyenneClasse: '11,2',
          minClasse: '3',
          maxClasse: '17',
        ),
        const GradeModel(
          id: 1005,
          devoir: 'DM - Statistiques',
          codePeriode: 'A002',
          codeMatiere: 'MATHS',
          libelleMatiere: 'Mathématiques',
          coef: '1',
          noteSur: '20',
          valeur: '17',
          date: '2026-01-28',
          moyenneClasse: '13,5',
        ),

        // ===== FRANÇAIS =====
        const GradeModel(
          id: 2001,
          devoir: 'Dictée',
          codePeriode: 'A001',
          codeMatiere: 'FRANC',
          libelleMatiere: 'Français',
          coef: '1',
          noteSur: '20',
          valeur: '13',
          date: '2025-09-18',
          moyenneClasse: '11,5',
        ),
        const GradeModel(
          id: 2002,
          devoir: 'Rédaction - Le récit fantastique',
          codePeriode: 'A001',
          codeMatiere: 'FRANC',
          libelleMatiere: 'Français',
          coef: '2',
          noteSur: '20',
          valeur: '15',
          date: '2025-10-10',
          moyenneClasse: '12,3',
          commentaire: 'Très bonne imagination, attention à l\'orthographe',
        ),
        const GradeModel(
          id: 2003,
          devoir: 'Contrôle de grammaire',
          codePeriode: 'A001',
          codeMatiere: 'FRANC',
          libelleMatiere: 'Français',
          coef: '1',
          noteSur: '20',
          valeur: '12',
          date: '2025-11-05',
          moyenneClasse: '10,8',
        ),
        const GradeModel(
          id: 2004,
          devoir: 'Commentaire de texte',
          codePeriode: 'A002',
          codeMatiere: 'FRANC',
          libelleMatiere: 'Français',
          coef: '2',
          noteSur: '20',
          valeur: '14',
          date: '2026-01-20',
          moyenneClasse: '11,5',
        ),

        // ===== HISTOIRE-GÉOGRAPHIE =====
        const GradeModel(
          id: 3001,
          devoir: 'Contrôle - La Révolution française',
          codePeriode: 'A001',
          codeMatiere: 'HIGE',
          libelleMatiere: 'Histoire-Géographie',
          coef: '2',
          noteSur: '20',
          valeur: '17',
          date: '2025-10-02',
          moyenneClasse: '13,2',
          maxClasse: '19',
        ),
        const GradeModel(
          id: 3002,
          devoir: 'Exposé - Les espaces productifs',
          codePeriode: 'A001',
          codeMatiere: 'HIGE',
          libelleMatiere: 'Histoire-Géographie',
          coef: '1',
          noteSur: '20',
          valeur: '16',
          date: '2025-11-15',
          moyenneClasse: '14,1',
        ),
        const GradeModel(
          id: 3003,
          devoir: 'Contrôle - L\'Europe au XIXe siècle',
          codePeriode: 'A002',
          codeMatiere: 'HIGE',
          libelleMatiere: 'Histoire-Géographie',
          coef: '2',
          noteSur: '20',
          valeur: '15',
          date: '2026-01-25',
          moyenneClasse: '12,8',
        ),

        // ===== ANGLAIS =====
        const GradeModel(
          id: 4001,
          devoir: 'Test de vocabulaire',
          codePeriode: 'A001',
          codeMatiere: 'AGL1',
          libelleMatiere: 'Anglais LV1',
          coef: '1',
          noteSur: '20',
          valeur: '18',
          date: '2025-09-25',
          moyenneClasse: '14,5',
        ),
        const GradeModel(
          id: 4002,
          devoir: 'Expression écrite',
          codePeriode: 'A001',
          codeMatiere: 'AGL1',
          libelleMatiere: 'Anglais LV1',
          coef: '2',
          noteSur: '20',
          valeur: '14',
          date: '2025-10-20',
          moyenneClasse: '12,2',
        ),
        const GradeModel(
          id: 4003,
          devoir: 'Compréhension orale',
          codePeriode: 'A002',
          codeMatiere: 'AGL1',
          libelleMatiere: 'Anglais LV1',
          coef: '1',
          noteSur: '20',
          valeur: '16',
          date: '2026-01-18',
          moyenneClasse: '13,8',
        ),

        // ===== ESPAGNOL =====
        const GradeModel(
          id: 5001,
          devoir: 'Vocabulaire - La famille',
          codePeriode: 'A001',
          codeMatiere: 'ESP2',
          libelleMatiere: 'Espagnol LV2',
          coef: '1',
          noteSur: '20',
          valeur: '15',
          date: '2025-10-08',
          moyenneClasse: '13,2',
        ),
        const GradeModel(
          id: 5002,
          devoir: 'Dialogue oral',
          codePeriode: 'A001',
          codeMatiere: 'ESP2',
          libelleMatiere: 'Espagnol LV2',
          coef: '1',
          noteSur: '20',
          valeur: '13',
          date: '2025-11-20',
          moyenneClasse: '12,5',
        ),
        const GradeModel(
          id: 5003,
          devoir: 'Contrôle - Conjugaison',
          codePeriode: 'A002',
          codeMatiere: 'ESP2',
          libelleMatiere: 'Espagnol LV2',
          coef: '2',
          noteSur: '20',
          valeur: '14',
          date: '2026-01-22',
          moyenneClasse: '11,8',
        ),

        // ===== PHYSIQUE-CHIMIE =====
        const GradeModel(
          id: 6001,
          devoir: 'TP - Les atomes',
          codePeriode: 'A001',
          codeMatiere: 'PHCH',
          libelleMatiere: 'Physique-Chimie',
          coef: '1',
          noteSur: '20',
          valeur: '16',
          date: '2025-09-28',
          moyenneClasse: '14,2',
        ),
        const GradeModel(
          id: 6002,
          devoir: 'Contrôle - L\'électricité',
          codePeriode: 'A001',
          codeMatiere: 'PHCH',
          libelleMatiere: 'Physique-Chimie',
          coef: '2',
          noteSur: '20',
          valeur: '13',
          date: '2025-11-08',
          moyenneClasse: '11,5',
        ),
        const GradeModel(
          id: 6003,
          devoir: 'TP - Réactions chimiques',
          codePeriode: 'A002',
          codeMatiere: 'PHCH',
          libelleMatiere: 'Physique-Chimie',
          coef: '1',
          noteSur: '20',
          valeur: '17',
          date: '2026-01-12',
          moyenneClasse: '13,8',
        ),

        // ===== SVT =====
        const GradeModel(
          id: 7001,
          devoir: 'Contrôle - La cellule',
          codePeriode: 'A001',
          codeMatiere: 'SVT',
          libelleMatiere: 'Sciences de la Vie et de la Terre',
          coef: '2',
          noteSur: '20',
          valeur: '14',
          date: '2025-10-15',
          moyenneClasse: '12,8',
        ),
        const GradeModel(
          id: 7002,
          devoir: 'Exposé - La biodiversité',
          codePeriode: 'A001',
          codeMatiere: 'SVT',
          libelleMatiere: 'Sciences de la Vie et de la Terre',
          coef: '1',
          noteSur: '20',
          valeur: '18',
          date: '2025-11-25',
          moyenneClasse: '15,2',
          commentaire: 'Excellent travail de recherche',
        ),
        const GradeModel(
          id: 7003,
          devoir: 'TP - Le système nerveux',
          codePeriode: 'A002',
          codeMatiere: 'SVT',
          libelleMatiere: 'Sciences de la Vie et de la Terre',
          coef: '1',
          noteSur: '20',
          valeur: '15',
          date: '2026-01-30',
          moyenneClasse: '13,5',
        ),

        // ===== TECHNOLOGIE =====
        const GradeModel(
          id: 8001,
          devoir: 'Projet - Programmation Scratch',
          codePeriode: 'A001',
          codeMatiere: 'TECHNO',
          libelleMatiere: 'Technologie',
          coef: '2',
          noteSur: '20',
          valeur: '19',
          date: '2025-10-25',
          moyenneClasse: '15,5',
          commentaire: 'Projet très abouti',
        ),
        const GradeModel(
          id: 8002,
          devoir: 'QCM - Énergie',
          codePeriode: 'A002',
          codeMatiere: 'TECHNO',
          libelleMatiere: 'Technologie',
          coef: '1',
          noteSur: '20',
          valeur: '16',
          date: '2026-01-10',
          moyenneClasse: '14,2',
        ),

        // ===== EPS =====
        const GradeModel(
          id: 9001,
          devoir: 'Course de demi-fond',
          codePeriode: 'A001',
          codeMatiere: 'EPS',
          libelleMatiere: 'Éducation Physique et Sportive',
          coef: '1',
          noteSur: '20',
          valeur: '15',
          date: '2025-10-12',
          moyenneClasse: '13,8',
        ),
        const GradeModel(
          id: 9002,
          devoir: 'Gymnastique',
          codePeriode: 'A001',
          codeMatiere: 'EPS',
          libelleMatiere: 'Éducation Physique et Sportive',
          coef: '1',
          noteSur: '20',
          valeur: '14',
          date: '2025-11-18',
          moyenneClasse: '14,5',
        ),
        const GradeModel(
          id: 9003,
          devoir: 'Natation',
          codePeriode: 'A002',
          codeMatiere: 'EPS',
          libelleMatiere: 'Éducation Physique et Sportive',
          coef: '1',
          noteSur: '20',
          valeur: '16',
          date: '2026-01-24',
          moyenneClasse: '13,2',
        ),

        // ===== ARTS PLASTIQUES =====
        const GradeModel(
          id: 10001,
          devoir: 'Production - Autoportrait',
          codePeriode: 'A001',
          codeMatiere: 'ARTS',
          libelleMatiere: 'Arts Plastiques',
          coef: '1',
          noteSur: '20',
          valeur: '17',
          date: '2025-10-30',
          moyenneClasse: '15,8',
        ),
        const GradeModel(
          id: 10002,
          devoir: 'Projet - Installation artistique',
          codePeriode: 'A002',
          codeMatiere: 'ARTS',
          libelleMatiere: 'Arts Plastiques',
          coef: '1',
          noteSur: '20',
          valeur: '18',
          date: '2026-01-27',
          moyenneClasse: '16,2',
        ),

        // ===== MUSIQUE =====
        const GradeModel(
          id: 11001,
          devoir: 'Pratique vocale',
          codePeriode: 'A001',
          codeMatiere: 'MUSIQ',
          libelleMatiere: 'Éducation Musicale',
          coef: '1',
          noteSur: '20',
          valeur: '14',
          date: '2025-11-10',
          moyenneClasse: '14,5',
        ),
        const GradeModel(
          id: 11002,
          devoir: 'Culture musicale',
          codePeriode: 'A002',
          codeMatiere: 'MUSIQ',
          libelleMatiere: 'Éducation Musicale',
          coef: '1',
          noteSur: '20',
          valeur: '15',
          date: '2026-01-16',
          moyenneClasse: '13,8',
        ),
      ];

  /// Informations sur les matières (pour subjectInfos)
  static Map<String, Map<String, dynamic>> get demoSubjectInfos => {
        'MATHS': {
          'name': 'Mathématiques',
          'teacher': 'M. Martin',
          'classAverage': 11.8,
        },
        'FRANC': {
          'name': 'Français',
          'teacher': 'Mme Dubois',
          'classAverage': 11.5,
        },
        'HIGE': {
          'name': 'Histoire-Géographie',
          'teacher': 'M. Bernard',
          'classAverage': 13.4,
        },
        'AGL1': {
          'name': 'Anglais LV1',
          'teacher': 'Mme Smith',
          'classAverage': 13.5,
        },
        'ESP2': {
          'name': 'Espagnol LV2',
          'teacher': 'Mme Garcia',
          'classAverage': 12.5,
        },
        'PHCH': {
          'name': 'Physique-Chimie',
          'teacher': 'M. Curie',
          'classAverage': 13.2,
        },
        'SVT': {
          'name': 'Sciences de la Vie et de la Terre',
          'teacher': 'Mme Pasteur',
          'classAverage': 13.8,
        },
        'TECHNO': {
          'name': 'Technologie',
          'teacher': 'M. Turing',
          'classAverage': 14.8,
        },
        'EPS': {
          'name': 'Éducation Physique et Sportive',
          'teacher': 'M. Coubertin',
          'classAverage': 13.8,
        },
        'ARTS': {
          'name': 'Arts Plastiques',
          'teacher': 'Mme Picasso',
          'classAverage': 16.0,
        },
        'MUSIQ': {
          'name': 'Éducation Musicale',
          'teacher': 'M. Mozart',
          'classAverage': 14.2,
        },
      };
}
